### ISSUE TITLE
Websites Down.

### ISSUE THREAD

**Issue by WujekStryjek** [zyrouge/web-status-monitor#1]

**Comment by WujekStryjek** [comment]
Hey dude.. hmu on Discord
WujekStryjek#4884

Need help with something. asap

**Comment by zyrouge** [comment]
Contact me on Discord: ZYROUGE#0950

**Comment by WujekStryjek** [comment]
You forgot the last number of your user.

**Comment by zyrouge** [comment]
GitHub hid one of the zeroes lol

**Comment by WujekStryjek** [comment]
Still doesnt work. You add my Discord which I included at the top

**Comment by zyrouge** [comment]
I can't add you on discord. Try joining my server https://discord.gg/8KV5zCg
